export type StaffMember = {
  id: string;
  division: '회원사업부' | '대외협력추진본부';
  name: string;
  department: string;
  title: string;
  position: string;
  extension: string;
  mobile: string;
  emergencyContact: string;
  email: string;
  tasks: string[];
};

export const staffMembers: StaffMember[] = [
  {
    id: 's1',
    division: '회원사업부',
    name: '전진헌',
    department: '회원사업부',
    title: '총괄',
    position: '부장',
    extension: '203',
    mobile: '-',
    emergencyContact: '-',
    email: 'huni94@korcham.net',
    tasks: [
      '신년인사회',
      '임원 간담회',
      '창립기념품 제공(당연)',
      '상의발전위원회(간사)',
      '회관건립추진위원회(간사)',
      'CEO아카데미(2년차)',
      '정관 및 규정 관리',
      '선거 및 회장 이·취임식',
      '경상연 총무부서장',
    ],
  },
  {
    id: 's2',
    division: '회원사업부',
    name: '김은희',
    department: '회원사업부',
    title: '회원',
    position: '차장',
    extension: '204',
    mobile: '-',
    emergencyContact: '-',
    email: 'heeyakim@korcham.net',
    tasks: [
      '회장배 골프대회',
      '회원 관리&회비(당연)',
      '회원 유치',
      '회원 현장소통',
      '회원 행사(수행포함)',
      '골프회(간사)',
      'CEO아카데미(1년차)',
      '제조물책임보험(PL) 지원사업',
      '산악회(간사)',
      '외부지원(총원우회, 뿌리회)',
      '경상연 회원부서장',
    ],
  },
  {
    id: 's3',
    division: '회원사업부',
    name: '김찬미',
    department: '회원사업부',
    title: '회계',
    position: '과장',
    extension: '208',
    mobile: '-',
    emergencyContact: '-',
    email: 'ley300@korcham.net',
    tasks: [
      '예산서/결산서',
      '여성기업위원회(간사)',
      '계좌&자금 관리',
      '회비 징수처리',
      '세무 신고',
      '감사(내/외부, 대한상의)',
      '인사(채용,연차,퇴직,상벌,복지)',
      '구매 및 처분',
      '사랑나눔 지원사업',
      '상의 내부(시무식,환경미화)',
      '회장님 일정 관리',
    ],
  },
  {
    id: 's4',
    division: '회원사업부',
    name: '유병우',
    department: '회원사업부',
    title: '회원사업',
    position: '대리',
    extension: '301',
    mobile: '-',
    emergencyContact: '-',
    email: 'demian9132@korcham.net',
    tasks: [
      '회원 관리&회비(임의/전사적)',
      '경기북부기우회',
      '상공대상 및 상공의날 시상',
      '회원 현판',
      '회원 훈포상',
      '회원 기업애로 접수',
      '회원 명절선물 발송(설,추석)',
      '건설기업위원회(간사)',
      '보조사업(전통시장)',
      '유통서비스기업위원회(간사)',
      '수출지원센터 운영',
    ],
  },
  {
    id: 's5',
    division: '회원사업부',
    name: '염동민',
    department: '회원사업부',
    title: '교육',
    position: '대리',
    extension: '207',
    mobile: '-',
    emergencyContact: '-',
    email: 'dmy130@korcham.net',
    tasks: [
      '실무 연간교육',
      '사업계획서',
      '실적보고서',
      '조찬강연 포럼',
      '청년기업인 포럼(위원회)',
      '대외기관 업무 및 협약',
      '회장님 인사말씀(연하장, 설, 추석, 행사)',
      '의원총회 및 상임위원회',
      '제조기업위원회(간사)',
    ],
  },
  {
    id: 's6',
    division: '회원사업부',
    name: '박민준',
    department: '회원사업부',
    title: '홍보/관리',
    position: '사원',
    extension: '305',
    mobile: '-',
    emergencyContact: '-',
    email: 'mj9457@korcham.net',
    tasks: [
      '상공 달력제작',
      '기업사랑뉴스',
      '상의 홍보(블로그,유튜브,홈페이지,카톡)',
      '회원 경조사',
      '회원 DB구축 및 ASP관리',
      '공용관리(교육장,대관,공용차량)',
      '문서 수발신(이메일,팩스)',
      '경상연',
      '회원 가입&탈퇴 처리',
      '드림팩스 DB 관리',
    ],
  },
  {
    id: 's7',
    division: '대외협력추진본부',
    name: '김정만',
    department: '대외협력추진본부',
    title: '검정(전담)',
    position: '주임',
    extension: '206',
    mobile: '-',
    emergencyContact: '-',
    email: 'kjm22321@korcham.net',
    tasks: ['검정사업 시행', '상설검정장 관리'],
  },
  {
    id: 's8',
    division: '대외협력추진본부',
    name: '이지은',
    department: '대외협력추진본부',
    title: '무역(전담)',
    position: '주임',
    extension: '302',
    mobile: '-',
    emergencyContact: '-',
    email: 'leejeanie96@korcham.net',
    tasks: ['시니어인턴(본부)', '무역증명', '원산지증명(FTA)', '방문인증 & 내용증명'],
  },
  {
    id: 's9',
    division: '대외협력추진본부',
    name: '서민우',
    department: '대외협력추진본부',
    title: '회계&서무',
    position: '주임',
    extension: '801',
    mobile: '-',
    emergencyContact: '-',
    email: 'smw1123@korcham.net',
    tasks: ['회계&서무(본부)', '왕숙지구위원회(간사/본부)', '공동인증서', '검정사업 기획'],
  },
  {
    id: 's10',
    division: '대외협력추진본부',
    name: '김상겸',
    department: '대외협력추진본부',
    title: '일자리사업',
    position: '본부장',
    extension: '308',
    mobile: '-',
    emergencyContact: '-',
    email: 'sangkyum@korcham.net',
    tasks: ['경상연 의전'],
  },
];
